"""
Django settings for plataforma project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
from os import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%7q!oc^x(8&saz4zvgh)+v+h$(kn1jqe*%srkzh#vsj^-c9!p)"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "grappelli",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'import_export',
    "rest_framework",
    "price",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "plataforma.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "plataforma.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": environ.get("DATABASE_NAME", "price"),
        "USER": environ.get("DATABASE_USER", "me"),
        "PASSWORD": environ.get("DATABASE_PASSWORD", "contrasena"),
        "HOST": environ.get("DATABASE_HOST", "postgres"),  # Cambiado a DATABASE_HOST
        "PORT": environ.get("DATABASE_PORT", 5432),       # Cambiado a DATABASE_PORT
        "CONN_MAX_AGE": 600,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

HARINAS_PANIFICADOS = {
    ('pan francés', 'pan francés'),
    ('galletitas dulces', 'galletitas dulces'),
    ('galletitas de agua', 'galletitas de agua'),
    ('harina de trigo', 'harina de trigo'),
    ('harina de maíz', 'harina de maíz'),
    ('fideos secos', 'fideos secos')
}
CEREALES_LEGUMBRES = {
    ('arroz', 'arroz'),
    ('arvejas en lata', 'arvejas en lata'),
    ('lentejas secas', 'lentejas secas'),
}

CARNES = {
    ('huevo', 'huevo'),
    ('asado', 'asado'),
    ('carnaza común', 'carnaza común'),
    ('hueso con carne', 'hueso con carne'),
    ('paleta', 'paleta'),
    ('carne picada', 'carne picada'),
    ('nalga', 'nalga'),
    ('hígado', 'hígado'),
    ('pechito de cerdo', 'pechito de cerdo'),
    ('pollo', 'pollo'),
    ('carne de pescado', 'carne de pescado'),
    ('mortadela', 'mortadela'),
    ('paleta cocida', 'paleta cocida'),
    ('salchichón', 'salchichón'),
    ('salame', 'salame'),
}

OLEOS = {
    ('aceite de girasol', 'aceite de girasol'),
    ('margarina para cocinar', 'margarina para cocinar'),
}

LACTEOS = {
    ('leche fluida', 'leche fluida'),
    ('leche en polvo entera', 'leche en polvo entera'),
    ('queso crema', 'queso crema'),
    ('queso cuartirolo', 'queso cuartirolo'),
    ('queso de rallar', 'queso de rallar'),
    ('manteca', 'manteca'),
    ('yogur', 'yogur'),
    ('dulce de leche', 'dulce de leche'),
}

FRUTAS = {
    ('manzana', 'manzana'),
    ('mandarina', 'mandarina'),
    ('naranja', 'naranja'),
    ('banana', 'banana'),
    ('pera', 'pera'),
}

VERDURAS_HORTALIZAS = {
    ('batata', 'batata'),
    ('papa', 'papa'),
    ('acelga', 'acelga'),
    ('cebolla', 'cebolla'),
    ('choclo', 'choclo'),
    ('lechuga', 'lechuga'),
    ('tomate perita', 'tomate perita'),
    ('zanahoria', 'zanahoria'),
    ('zapallo', 'zapallo'),
    ('tomate envasado', 'tomate envasado'),
}


DULCES = {
    ('azúcar', 'azúcar'),
    ('dulce de batata', 'dulce de batata'),
    ('mermelada', 'mermelada'),
}


CONDIMENTOS = {
    ('sal fina', 'sal fina'),
    ('mayonesa', 'mayonesa'),
    ('vinagre', 'vinagre'),
    ('caldo concentrado', 'caldo concentrado'),    
}

BEBIDAS = {
    ('gaseosas', 'gaseosas'),
    ('jugos concentrados', 'jugos concentrados'),
    ('soda', 'soda'),
    ('cerveza', 'cerveza'),
    ('vino', 'vino'),
}

INFUCIONES = {
    ('café', 'café'),
    ('yerba', 'yerba'),
    ('te en saquitos', 'te en saquitos'),
}

