# Generated by Django 4.2 on 2024-04-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='producto',
            field=models.CharField(choices=[('pan francés', 'pan francés'), ('galletitas dulces', 'galletitas dulces'), ('galletitas de agua', 'galletitas de agua'), ('harina de trigo', 'harina de trigo'), ('harina de maíz', 'harina de maíz'), ('arroz', 'arroz'), ('fideos secos', 'fideos secos'), ('asado', 'asado'), ('carnaza común', 'carnaza común'), ('hueso con carne', 'hueso con carne'), ('paleta', 'paleta'), ('carne picada', 'carne picada'), ('nalga', 'nalga'), ('hígado', 'hígado'), ('pechito de cerdo', 'pechito de cerdo'), ('pollo', 'pollo'), ('carne de pescado', 'carne de pescado'), ('mortadela', 'mortadela'), ('paleta cocida', 'paleta cocida'), ('salchichón', 'salchichón'), ('salame', 'salame'), ('aceite de girasol', 'aceite de girasol'), ('margarina para cocinar', 'margarina para cocinar'), ('leche fluida', 'leche fluida'), ('leche en polvo entera', 'leche en polvo entera'), ('queso crema', 'queso crema'), ('queso cuartirolo', 'queso cuartirolo'), ('queso de rallar', 'queso de rallar'), ('manteca', 'manteca'), ('yogur', 'yogur'), ('dulce de leche', 'dulce de leche'), ('huevo', 'huevo'), ('manzana', 'manzana'), ('mandarina', 'mandarina'), ('naranja', 'naranja'), ('banana', 'banana'), ('pera', 'pera'), ('batata', 'batata'), ('papa', 'papa'), ('acelga', 'acelga'), ('cebolla', 'cebolla'), ('choclo', 'choclo'), ('lechuga', 'lechuga'), ('tomate perita', 'tomate perita'), ('zanahoria', 'zanahoria'), ('zapallo', 'zapallo'), ('tomate envasado', 'tomate envasado'), ('arvejas en lata', 'arvejas en lata'), ('lentejas secas', 'lentejas secas'), ('azúcar', 'azúcar'), ('dulce de batata', 'dulce de batata'), ('mermelada', 'mermelada'), ('sal fina', 'sal fina'), ('mayonesa', 'mayonesa'), ('vinagre', 'vinagre'), ('caldo concentrado', 'caldo concentrado'), ('gaseosas', 'gaseosas'), ('jugos concentrados', 'jugos concentrados'), ('soda', 'soda'), ('cerveza', 'cerveza'), ('vino', 'vino'), ('café', 'café'), ('yerba', 'yerba'), ('te en saquitos', 'te en saquitos')], max_length=100),
        ),
    ]
